rabbit1:
  image: harbur/rabbitmq-cluster
  hostname: rabbit1
  environment:
   - ERLANG_COOKIE=abcdefg
  ports:
   - "5672:5672"
   - "55672:55672"
  command: /usr/lib/rabbitmq/bin/rabbitmq-plugins enable rabbitmq_management
rabbit2:
  image: harbur/rabbitmq-cluster
  hostname: rabbit2
  links:
   - rabbit1
  environment:
   - ERLANG_COOKIE=abcdefg
   - CLUSTER_WITH=rabbit1
  ports:
   - "5673:5672"
   - "55672:55672"
  command: /usr/lib/rabbitmq/bin/rabbitmq-plugins enable rabbitmq_management
